package island.enums;

public enum Names {Watchtower,
    		WhisperingGarden,
    		Observatory,
    		DunesOfDeception,
    		CliffsOfAgandon,
    		BreakersBridge,
    		TwilightHollow,
    		BronzeGate,
    		CopperGate,
    		FoolsLanding,
    		MistyMarsh,
    		TempleOfTheSun,
    		TempleOfTheMoon,
    		LostLagoon,
    		GoldGate,
    		CoralPalace,
    		CaveOfEmbers,
    		TidalPalace,
    		CaveOfShadows,
    		CrimsonForest,
    		HowlingGarden,
    		IronGate,
    		SilverGate,
    		PhantomRock
}
